FROM node:18

WORKDIR /app/neo4j

# Copiar dependencias
COPY neo4j/package.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY neo4j ./

# Instalar netcat para esperar a Neo4j
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Script para esperar a que esté listo Neo4j
COPY wait-for-neo4j.sh /app/wait-for-neo4j.sh
RUN chmod +x /app/wait-for-neo4j.sh

CMD ["/app/wait-for-neo4j.sh"]
