FROM python:3.10-slim

WORKDIR /app

# Instalar solo la dependencia necesaria
RUN pip install neo4j

# Copiar scripts
COPY neo4j/carga_grafos.py /app/
COPY csv_exports /app/csv_exports/

CMD ["python", "/app/carga_grafos.py"]