FROM apache/spark:4.0.0

USER root
RUN apt-get update && \
    apt-get install -y openjdk-17-jre-headless python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN pip install --no-cache-dir python-dotenv

USER spark