FROM node:18

WORKDIR /app

# Copiar solo los archivos necesarios
COPY package*.json db/fill_postgres.js ./db/
RUN cd db && npm install

# Definir directorio de ejecución
WORKDIR /app/db

CMD ["node", "fill_postgres.js"]
