version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: restaurant
    ports:
      - "5432:5432"
  api:
    build: .
    environment:
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: restaurant
      DB_HOST: db
      DB_PORT: 5432
      JWT_SECRET: your_jwt_secret
    ports:
      - "5000:5000"
    depends_on:
      - db