openapi: 3.0.0
info:
  title: Restaurante API
  description: API documentation for Restaurante
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local development server

paths:
  /auth/register:
    post:
      summary: Register a new user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
