name: CI/CD Pipeline

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (API)
        working-directory: ./src/api
        run: npm install

      - name: Run tests (API)
        working-directory: ./src/api
        run: npm test

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurantes-e2-api:latest -f src/api/Dockerfile .

      - name: Build Search image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/restaurantes-e2-search:latest -f src/search/Dockerfile .

      - name: Push API image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/restaurantes-e2-api:latest

      - name: Push Search image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/restaurantes-e2-search:latest
